.\"     Title: guilt-help
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 07/17/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-HELP" "1" "07/17/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt\-help \- open man page of a guilt command
.SH "SYNOPSIS"
\fIguilt\-help\fR [<command> | <topic>]
.SH "DESCRIPTION"
Open up the man page for a guilt command.
.SH "EXAMPLES"
Open the guilt\-status man page

$ guilt\-help status

Open the guilt man page

$ guilt\-help
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "DOCUMENTATION"
Documentation by Brandon Philips <brandon@ifup.org>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.26)

