.\"     Title: guilt-commit
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 09/05/2008
.\"    Manual: Guilt Manual
.\"    Source: Guilt v0.31
.\"
.TH "GUILT\-COMMIT" "1" "09/05/2008" "Guilt v0\&.31" "Guilt Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt-commit \- Commit specified number of patches
.SH "SYNOPSIS"
\fIguilt\-commit\fR \-n <num> | \-a | \-\-all

Turn specified number of bottom most patches into Git commits\&. This removes the the patches from the series, and status file\&.
.SH "OPTIONS"
.PP
\-\-all, \-a
.RS 4
Commit all applied patches
.RE
.PP
\-n <num>
.RS 4
Commit <num> bottom most patches
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <\fIjeffpc@josefsipek\&.net\fR\&[1]>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <\fIjeffpc@josefsipek\&.net\fR\&[1]>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0\&.31)
.SH "NOTES"
.IP " 1." 4
jeffpc@josefsipek.net
.RS 4
\%mailto:jeffpc@josefsipek.net
.RE
