.\"     Title: guilt-diff
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 07/17/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-DIFF" "1" "07/17/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt\-diff \- Outputs various diffs
.SH "SYNOPSIS"
\fIguilt\-diff\fR [\-z]
.SH "DESCRIPTION"
Outputs top\-most applied diff and any additional changes in the working directory to stdout.
.SH "OPTIONS"
.PP
\-z
.RS 4
Output a interdiff against the top\-most applied patch. This should produce the same diff as "guilt\-new \-f foo".
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.26)

