.\"     Title: guilt-series
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 08/01/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-SERIES" "1" "08/01/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt\-series \- Print the stack of patches
.SH "SYNOPSIS"
\fIguilt\-series\fR [\-v | \-g | \-e]
.SH "DESCRIPTION"
Print the stack of patches on this branch.
.SH "OPTIONS"
.PP
\-e
.RS 4
Edit the series file.
.RE
.PP
\-g
.RS 4
Instead of outputing the series, start gitk and display the applied patches. Ignores the verbose flag.
.RE
.PP
\-v
.RS 4
Verbose output; adds an = next to the top most applied patch, and a + to all other applied patches
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.26)

