.\"     Title: guilt\-prev
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 03/20/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-PREV" "1" "03/20/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt\-prev \- Output name of second topmost applied patch
.SH "SYNOPSIS"
\fIguilt\-prev\fR
.SH "DESCRIPTION"
Output name of second topmost applied patch. If \fBguilt\-pop\fR(1) is used, this patch will become the topmost patch.
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.23)

