.\"     Title: guilt-push
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 04/10/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-PUSH" "1" "04/10/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt-push \- Push patches onto the tree
.SH "SYNOPSIS"
\fIguilt\-push\fR [ \-f ] [\-a | \-\-all | \-n <num> | <patchname>]
.SH "OPTIONS"
.PP
\-f
.RS 4
Force the push if the patch doesn\'t apply cleanly
.RE
.PP
\-\-all, \-a
.RS 4
Push all patches on the tree
.RE
.PP
\-n <num>
.RS 4
Push specified number of patches
.RE
.PP
<patchname>
.RS 4
Push all patches up to and including this patch on the tree
.RE
If no patchname is given, push the next patch in the series onto the tree\.
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jeffpc@josefsipek\.net>
.SH "DOCUMENTATION"
Documentation by Brandon Philips <brandon@ifup\.org>
.SH "GUILT"
Part of the guilt\fI7\fR\&[1] suite (Generated for Guilt v0\.30)
.SH "NOTES"
.IP " 1." 4
7
.RS 4
\%guilt
.RE
