.\"     Title: guilt-applied
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 08/01/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-APPLIED" "1" "08/01/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt\-applied \- List applied patches
.SH "SYNOPSIS"
\fIguilt\-applied\fR [\-c]
.SH "DESCRIPTION"
Prints a list of all applied patches.
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "DOCUMENTATION"
Documentation by Brandon Philips <brandon@ifup.org>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.26)

