.\"     Title: guilt\-files
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 04/17/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-FILES" "1" "04/17/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt\-files \- Print the list of files that the topmost patch changes
.SH "SYNOPSIS"
\fIguilt\-files\fR [\-v] [\-a] [\-l]
.SH "DESCRIPTION"
Print the list of files that the topmost patch changes.
.SH "OPTIONS"
.PP
\-v
.RS 3n
Verbose output
.RE
.PP
\-a
.RS 3n
List all files in all applied patches
.RE
.PP
\-l
.RS 3n
Add patch name to the output
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.24)

