.\"     Title: guilt-pop
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 01/16/2009
.\"    Manual: Guilt Manual
.\"    Source: Guilt v0.32
.\"
.TH "GUILT\-POP" "1" "01/16/2009" "Guilt v0\&.32" "Guilt Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt-pop \- Pop patches from the tree
.SH "SYNOPSIS"
\fIguilt\-pop\fR [\-f] [\-a | \-\-all | \-n <num> | <patchname>]
.SH "OPTIONS"
.PP
\-\-all, \-a
.RS 4
Pop all patches off the tree
.RE
.PP
\-f
.RS 4
Force; discards any unrefreshed changes
.RE
.PP
\-n <num>
.RS 4
Push specified number of patches
.RE
.PP
<patchname>
.RS 4
Pop all patches up to and including this patch off the tree
.RE
If no patchname is given, pop the top\-most patch\&.
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <\fIjeffpc@josefsipek\&.net\fR\&[1]>
.SH "DOCUMENTATION"
Documentation by Brandon Philips <\fIbrandon@ifup\&.org\fR\&[2]>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0\&.32)
.SH "NOTES"
.IP " 1." 4
jeffpc@josefsipek.net
.RS 4
\%mailto:jeffpc@josefsipek.net
.RE
.IP " 2." 4
brandon@ifup.org
.RS 4
\%mailto:brandon@ifup.org
.RE
