.\"     Title: guilt-diff
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 01/16/2009
.\"    Manual: Guilt Manual
.\"    Source: Guilt v0.32
.\"
.TH "GUILT\-DIFF" "1" "01/16/2009" "Guilt v0\&.32" "Guilt Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt-diff \- Outputs various diffs
.SH "SYNOPSIS"
\fIguilt\-diff\fR [\-z] [<path>\&...]
.SH "DESCRIPTION"
Outputs top\-most applied diff and any additional changes in the working directory to standard output\&.
.SH "OPTIONS"
.PP
\-z
.RS 4
Output a interdiff against the top\-most applied patch\&. This should produce the same diff as "guilt\-new \-f foo"\&.
.RE
.PP
<path>\&...
.RS 4
Restrict diff output to a given set of files\&.
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <\fIjeffpc@josefsipek\&.net\fR\&[1]>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <\fIjeffpc@josefsipek\&.net\fR\&[1]>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0\&.32)
.SH "NOTES"
.IP " 1." 4
jeffpc@josefsipek.net
.RS 4
\%mailto:jeffpc@josefsipek.net
.RE
