.\"     Title: guilt-header
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/19/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-HEADER" "1" "11/19/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt-header - Print a patch header
.SH "SYNOPSIS"
\fIguilt\-header\fR [\-e] [<patchname>]
.SH "DESCRIPTION"
Prints either the topmost patch\'s header or the header of a specified patch\.
.PP
\-e
.RS 4
Open the header in an editor, instead of printing it\.
.RE
.PP
<patchname>
.RS 4
Name of the patch\.
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jsipek@cs\.sunysb\.edu>
.SH "DOCUMENTATION"
Documentation by Brandon Philips <brandon@ifup\.org>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0\.28)

