.\"     Title: guilt-import
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 07/17/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-IMPORT" "1" "07/17/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt\-import \- Import specified patch file
.SH "SYNOPSIS"
\fIguilt\-import\fR [\-P <patch> ] <patch_file>
.SH "DESCRIPTION"
Import a specified patch file into the series, placing it after the current topmost patch.
.SH "OPTIONS"
.PP
\-P <patch>
.RS 4
Name of the patch within Guilt.
.RE
.PP
<patch_file>
.RS 4
Name of the file to be imported into the series.
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.26)

