.\"     Title: guilt-diff
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 04/10/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-DIFF" "1" "04/10/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt-diff \- Outputs various diffs
.SH "SYNOPSIS"
\fIguilt\-diff\fR [\-z]
.SH "DESCRIPTION"
Outputs top\-most applied diff and any additional changes in the working directory to stdout\.
.SH "OPTIONS"
.PP
\-z
.RS 4
Output a interdiff against the top\-most applied patch\. This should produce the same diff as "guilt\-new \-f foo"\.
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jeffpc@josefsipek\.net>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <jeffpc@josefsipek\.net>
.SH "GUILT"
Part of the guilt\fI7\fR\&[1] suite (Generated for Guilt v0\.30)
.SH "NOTES"
.IP " 1." 4
7
.RS 4
\%guilt
.RE
