.\"     Title: guilt-prev
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 09/05/2008
.\"    Manual: Guilt Manual
.\"    Source: Guilt v0.31
.\"
.TH "GUILT\-PREV" "1" "09/05/2008" "Guilt v0\&.31" "Guilt Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt-prev \- Output name of second topmost applied patch
.SH "SYNOPSIS"
\fIguilt\-prev\fR [\-p|\-\-path]
.SH "DESCRIPTION"
Output name of second topmost applied patch\&. If \fBguilt-pop\fR(1) is used, this patch will become the topmost patch\&.
.SH "OPTIONS"
.PP
\-p, \-\-path
.RS 4
Output full path instead of just patch name\&.
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <\fIjeffpc@josefsipek\&.net\fR\&[1]>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <\fIjeffpc@josefsipek\&.net\fR\&[1]>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0\&.31)
.SH "NOTES"
.IP " 1." 4
jeffpc@josefsipek.net
.RS 4
\%mailto:jeffpc@josefsipek.net
.RE
