.\"     Title: guilt-next
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 05/15/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-NEXT" "1" "05/15/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt\-next \- Output the name of next patch to be pushed
.SH "SYNOPSIS"
\fIguilt\-next\fR
.SH "DESCRIPTION"
Output the name of next patch to be pushed. If guilt\-push(1) is issued, this patch would be the topmost patch.
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.25)

