.\"     Title: guilt-fold
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 07/17/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-FOLD" "1" "07/17/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt\-fold \- Fold a specified patch into the topmost applied patch
.SH "SYNOPSIS"
\fIguilt\-fold\fR [\-k] <patchname>
.SH "OPTIONS"
.PP
\-k
.RS 4
Do not remove the patch file.
.RE
.PP
<patchname>
.RS 4
Fold this patch into the topmost applied patch. \fIpatchname\fR is removed from the series, as well as from the patches directory. (A backup file is created.)
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.26)

