.\"     Title: guilt-top
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/19/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-TOP" "1" "11/19/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt-top - Output name of topmost applied patch
.SH "SYNOPSIS"
\fIguilt\-top\fR [\-p|\-\-path]
.SH "OPTIONS"
.PP
\-p, \-\-path
.RS 4
Output full path instead of just patch name\.
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jsipek@cs\.sunysb\.edu>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <jsipek@cs\.sunysb\.edu>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0\.28)

