.\"     Title: guilt-branch
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 01/16/2009
.\"    Manual: Guilt Manual
.\"    Source: Guilt v0.32
.\"
.TH "GUILT\-BRANCH" "1" "01/16/2009" "Guilt v0\&.32" "Guilt Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt-branch \- Branch the entire patch series
.SH "SYNOPSIS"
\fIguilt\-branch\fR [<new_name>]
.SH "DESCRIPTION"
Create a copy of the entire branch patch directory (\&.git/patches/<branch>) to (\&.git/patches/<new_name>), create a new git branch <new_name> and check it out\&.
.SH "OPTIONS"
.PP
<new_name>
.RS 4
The name of the new branch to create\&. If not specified, the current branch name is appended with the current year, month and day\&.
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <\fIjeffpc@josefsipek\&.net\fR\&[1]>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <\fIjeffpc@josefsipek\&.net\fR\&[1]>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0\&.32)
.SH "NOTES"
.IP " 1." 4
jeffpc@josefsipek.net
.RS 4
\%mailto:jeffpc@josefsipek.net
.RE
