.\"     Title: guilt-init
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/19/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-INIT" "1" "11/19/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt-init - Initialize guilt for use in a git repository
.SH "SYNOPSIS"
\fIguilt\-init\fR [\-n]
.SH "DESCRIPTION"
Initialize a git repository for use with guilt
.SH "OPTIONS"
.PP
\-n
.RS 4
Do not automatically create stack top, bottom, and base tags (sets guilt\.autotag config variable to 0)\.
.RE
.SH "EXAMPLES"
First, get a repository to work on\. Here\'s one that we\'ll use as an example:

$ git\-clone git://git\.kernel\.org/pub/scm/linux/kernel/jsipek/guilt\-hello\.git

Now, it initialize the patches directory using guilt\'s init command:

$ cd hello

$ guilt\-init
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jsipek@cs\.sunysb\.edu>
.SH "DOCUMENTATION"
Documentation by Brandon Philips <brandon@ifup\.org>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0\.28)

