.\"     Title: guilt-graph
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 04/10/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-GRAPH" "1" "04/10/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt-graph \- Create a patch dependency graph
.SH "SYNOPSIS"
\fIguilt\-graph\fR [<patchname>]
.SH "DESCRIPTION"
Create a dot(1) directed graph showing the dependencies between applied patches\.
.SH "OPTIONS"
.PP
<patchname>
.RS 4
Instead of starting with the topmost applied patch, start with <patchname>\.
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jeffpc@josefsipek\.net>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <jeffpc@josefsipek\.net>
.SH "GUILT"
Part of the guilt\fI7\fR\&[1] suite (Generated for Guilt v0\.30)
.SH "NOTES"
.IP " 1." 4
7
.RS 4
\%guilt
.RE
