.\"     Title: guilt-fork
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 05/15/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-FORK" "1" "05/15/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt\-fork \- Fork the topmost applied patch
.SH "SYNOPSIS"
\fIguilt\-fork\fR [<new_name>]
.SH "DESCRIPTION"
Create a copy of the top most patch, and replace the entry in the series file to use this new patch file.
.SH "OPTIONS"
.PP
<new_name>
.RS 4
The name of the new patch to create.
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.25)

