.\"     Title: guilt-new
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 01/16/2009
.\"    Manual: Guilt Manual
.\"    Source: Guilt v0.32
.\"
.TH "GUILT\-NEW" "1" "01/16/2009" "Guilt v0\&.32" "Guilt Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt-new \- Create a new patch
.SH "SYNOPSIS"
\fIguilt\-new\fR [\-f] [\-s] [\-e|\-m message] <patchname>
.SH "DESCRIPTION"
Create a new patch and push it on top of the stack\&. An optional patch description can be supplied either interactively on via the command line\&.
.SH "OPTIONS"
.PP
\-f
.RS 4
Force patch creation if there are unrefreshed changes\&. These changes will get automatically imported into the new patch\&.
.RE
.PP
\-s
.RS 4
Add a Signed\-off\-by with your committer identifier string to the patch message\&.
.RE
.PP
\-e
.RS 4
Edit the patch message interactively\&. This option can be combined with \-s to easily sign off on the patch\&.
.RE
.PP
\-m <message>
.RS 4
The "<message>" string will used as the commit message\&. This option can be combined with \-s to easily sign off on the patch\&.
.RE
.PP
<patchname>
.RS 4
Name of the patch to create\&. This must be a legal relative pathname string\&. For example, "foo", "foo/bar", and "foo/bar/foobar" are all valid\&.
.RE
.SH "EXAMPLES"
Create a new patch called \fIfoobar\fR:

.sp
.RS 4
.nf
$ guilt\-new foobar
.fi
.RE
Create a patch called \fIfoo\fR and supply a patch description interactively:

.sp
.RS 4
.nf
$ guilt\-new \-e foo
.fi
.RE
Create a patch called \fIbar\fR with a provided patch description and sign off on the patch:

.sp
.RS 4
.nf
$ guilt\-new \-s \-m patch\-fu bar
.fi
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <\fIjeffpc@josefsipek\&.net\fR\&[1]>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <\fIjeffpc@josefsipek\&.net\fR\&[1]>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0\&.32)
.SH "NOTES"
.IP " 1." 4
jeffpc@josefsipek.net
.RS 4
\%mailto:jeffpc@josefsipek.net
.RE
