.\"     Title: guilt-delete
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 01/16/2009
.\"    Manual: Guilt Manual
.\"    Source: Guilt v0.32
.\"
.TH "GUILT\-DELETE" "1" "01/16/2009" "Guilt v0\&.32" "Guilt Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt-delete \- Delete a patch
.SH "SYNOPSIS"
\fIguilt\-delete\fR [\-f] <patchname>
.SH "DESCRIPTION"
Delete an unapplied patch from the series\&.
.SH "OPTIONS"
.PP
\-f
.RS 4
Remove the patch from the series and disk
.RE
.PP
<patchname>
.RS 4
Name of the patch to delete\&.
.RE
.SH "EXAMPLES"
Delete a patch called \fIfoobar\fR:

.sp
.RS 4
.nf
$ guilt\-delete foobar
.fi
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <\fIjeffpc@josefsipek\&.net\fR\&[1]>
.SH "DOCUMENTATION"
Documentation by Brandon Philips <\fIbrandon@ifup\&.org\fR\&[2]>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0\&.32)
.SH "NOTES"
.IP " 1." 4
jeffpc@josefsipek.net
.RS 4
\%mailto:jeffpc@josefsipek.net
.RE
.IP " 2." 4
brandon@ifup.org
.RS 4
\%mailto:brandon@ifup.org
.RE
