.\"     Title: guilt-add
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 07/17/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-ADD" "1" "07/17/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt\-add \- Add a file to git and guilt
.SH "SYNOPSIS"
\fIguilt\-add\fR <file>\&...
.SH "DESCRIPTION"
Adds the files specified to git using git\-add making it available to guilt.
.SH "OPTIONS"
.PP
<files>
.RS 4
Files to add
.RE
.SH "EXAMPLES"
Create and add a new file example.c

$ touch example.c $ guilt\-add example.c
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "DOCUMENTATION"
Documentation by Brandon Philips <brandon@ifup.org>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.26)

