.\"     Title: guilt\-series
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 03/20/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-SERIES" "1" "03/20/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt\-series \- Print the stack of patches
.SH "SYNOPSIS"
\fIguilt\-series\fR [\-v]
.SH "DESCRIPTION"
Print the stack of patches on this branch.
.PP
\-v
.RS 3n
Add a + next to the top most applied patch
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <jsipek@cs.sunysb.edu>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.23)

