.\"     Title: guilt-push
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 09/05/2008
.\"    Manual: Guilt Manual
.\"    Source: Guilt v0.31
.\"
.TH "GUILT\-PUSH" "1" "09/05/2008" "Guilt v0\&.31" "Guilt Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt-push \- Push patches onto the tree
.SH "SYNOPSIS"
\fIguilt\-push\fR [ \-f ] [\-a | \-\-all | \-n <num> | <patchname>]
.SH "OPTIONS"
.PP
\-f
.RS 4
Force the push if the patch doesn\'t apply cleanly
.RE
.PP
\-\-all, \-a
.RS 4
Push all patches on the tree
.RE
.PP
\-n <num>
.RS 4
Push specified number of patches
.RE
.PP
<patchname>
.RS 4
Push all patches up to and including this patch on the tree
.RE
If no patchname is given, push the next patch in the series onto the tree\&.
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <\fIjeffpc@josefsipek\&.net\fR\&[1]>
.SH "DOCUMENTATION"
Documentation by Brandon Philips <\fIbrandon@ifup\&.org\fR\&[2]>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0\&.31)
.SH "NOTES"
.IP " 1." 4
jeffpc@josefsipek.net
.RS 4
\%mailto:jeffpc@josefsipek.net
.RE
.IP " 2." 4
brandon@ifup.org
.RS 4
\%mailto:brandon@ifup.org
.RE
