.\"     Title: guilt-fork
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 03/19/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "GUILT\-FORK" "1" "03/19/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt-fork - Fork the topmost applied patch
.SH "SYNOPSIS"
\fIguilt\-fork\fR [<new_name>]
.SH "DESCRIPTION"
Create a copy of the top most patch, and replace the entry in the series file to use this new patch file\.
.SH "OPTIONS"
.PP
<new_name>
.RS 4
The name of the new patch to create\.
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <jsipek@cs\.sunysb\.edu>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <jsipek@cs\.sunysb\.edu>
.SH "GUILT"
Part of the guilt\fI7\fR\&[1] suite (Generated for Guilt v0\.29)
.SH "NOTES"
.IP " 1." 4
7
.RS 4
\%guilt
.RE
