.\"     Title: guilt-refresh
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 09/05/2008
.\"    Manual: Guilt Manual
.\"    Source: Guilt v0.31
.\"
.TH "GUILT\-REFRESH" "1" "09/05/2008" "Guilt v0\&.31" "Guilt Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt-refresh \- Refresh topmost applied patch
.SH "SYNOPSIS"
\fIguilt\-refresh\fR [\-\-git] [\-\-diffstat]
.SH "DESCRIPTION"
Refresh topmost applied patch with changes in the working copy\&.
.SH "OPTIONS"
.PP
\-\-git
.RS 4
Generate a patch which uses all the features offered by the git diff format (e\&.g\&., rename and copy detection)\&.
.RE
.PP
\-\-diffstat
.RS 4
Include a diffstat output in the patch file\&. Useful for cases where patches will be submitted with other tools\&.
.RE
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <\fIjeffpc@josefsipek\&.net\fR\&[1]>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <\fIjeffpc@josefsipek\&.net\fR\&[1]>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0\&.31)
.SH "NOTES"
.IP " 1." 4
jeffpc@josefsipek.net
.RS 4
\%mailto:jeffpc@josefsipek.net
.RE
