#!/bin/bash

function find_git_dir
{
	# let the user override
	if [ ! -z "$GIT_DIR" ]; then
		echo "$GIT_DIR"
		return
	fi

	DIR=`pwd`
	while true; do
		if [ -d "$DIR/.git" ]; then
			echo "$DIR/.git"
			return
		fi

		DIR2=`dirname $DIR`
		if [ "$DIR" = "$DIR2" ]; then
			echo "Could not find .git"
			exit 1
		fi
		DIR="$DIR2"
	done
}

DIR=`find_git_dir`

echo "Dir at: $DIR"

