#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006
#

source "`dirname $0`/gq.lib"

patch="$1"

if [ -z "$patch" ]; then
	echo "You must specify a patch to delete"
	exit 1
fi

p=`cat "$applied" | grep -e "^$patch\$"`
if [ ! -z "$p" ] ; then
	echo "Cannot delete an applied patch"
	exit 1
fi

ex -s -c ":%g/^foobar$/d|:wq" "$series"
