#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006
#

DO_NOT_CHECK_BRANCH_EXISTENCE=1

source "`dirname $0`/gq.lib"

if [ -d "$GQ_DIR/$branch" ]; then
	echo "Branch $branch appears to be already initialized (GIT_DIR=$GIT_DIR)"
	exit 1
fi

[ ! -d "$GQ_DIR" ] && mkdir $GQ_DIR
mkdir $GQ_DIR/$branch
touch $GQ_DIR/$branch/series
touch $GQ_DIR/$branch/status

