#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006
#

source "`dirname $0`/gq.lib"

patch="$1"

if [ -z "$patch" ]; then
	echo "You must specify a patch name"
	exit 1
else
	iidx=`wc -l < $applied`
fi

# make sure that there are no unapplied changes
if ! must_commit_first; then
	echo "Uncommited changes detected. Refresh first."
	exit 1
fi

# create the empty patch file
touch $GQ_DIR/$branch/$patch

top=`get_top`

if [ ! -z "$top" ]; then
	sed -i -e "s,^$top\$,$top\n$patch," $series
else
	echo $patch >> $series
fi

# apply the patch
push_patch $patch
echo $patch >> $applied
