#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006
#

source "`dirname $0`/gq.lib"

export GIT_DIR=`find_git_dir`
GQ_DIR="$GIT_DIR/patches"

branch=`get_branch_verify`
series="$GQ_DIR/$branch/series"
applied="$GQ_DIR/$branch/status"

# FIXME: ...
[ $# -ne 0 ] && echo "Poping only top most patch..arguments ignored"

# make sure that there are no unapplied changes
if ! must_commit_first; then
	echo "Uncommited changes detected. Refresh first."
	exit 1
fi

git reset --hard HEAD^

echo "Poping `get_top`..."

head -n -1 < $applied > $applied.tmp
mv $applied{.tmp,}

p=`get_top`
[ ! -z "$p" ] && echo "Now at $p." || echo "All patches popped."

