#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006
#

source "`dirname $0`/gq.lib"

export GIT_DIR=`find_git_dir`
GQ_DIR="$GIT_DIR/patches"

branch=`get_branch_verify`
series="$GQ_DIR/$branch/series"
applied="$GQ_DIR/$branch/status"

patch="$1"

if [ "$patch" = "--all" -o "$patch" = "-a" ]; then
	# we are supposed to push all patches, get the last one out of
	# series

	eidx=`wc -l < $series`
	if [ $eidx -eq 0 ]; then
		echo "There are no patches to push"
		exit 1
	fi
elif [ -z "$patch" ]; then
	# we are supposed to push only the next patch onto the stack

	eidx=`wc -l < $applied`
	eidx=`expr $eidx + 1`
else
	# we're supposed to push only up to a patch, make sure the patch is
	# in the series

	eidx=`cat $series | grep -ne "^$patch\$" | cut -d: -f1`
	if [ $eidx -eq 0 ]; then
		echo "Patch $patch is not in the series"
		exit 1
	fi
fi

# make sure that there are no unapplied changes
if ! must_commit_first; then
	echo "Uncommited changes detected. Refresh first."
	exit 1
fi

# now, find the starting patch
sidx=`wc -l < $applied`
sidx=`expr $sidx + 1`

bail=0
idx=0
for p in `cat $series`; do
	idx=`expr $idx + 1`
	[ $idx -lt $sidx ] && continue
	[ $idx -gt $eidx ] && break

	echo "Applying patch..$p"
	if [ ! -f "$GQ_DIR/$branch/$p" ]; then
		echo "Patch $patch does not exist. Aborting."
		exit 1
	fi

	push_patch $p
	bail=$?

	# mark patch as applied
	echo $p >> $applied

	# bail if necessary
	if [ $bail -eq 0 ]; then
		echo "Patch applied."
	else
		echo "Patch applied with rejects. Fix it up, and refresh."
		exit 1
	fi
done

