#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006
#

source "`dirname $0`/gq.lib"

export GIT_DIR=`find_git_dir`
GQ_DIR="$GIT_DIR/patches"

branch=`get_branch_verify`

TOP=`get_top`

refresh_patch "$TOP"

git-reset --hard HEAD^

push_patch "$TOP"

