#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006
#

source "`dirname $0`/gq.lib"

n=`wc -l < $applied`
n=`expr $n + 1`

idx=0
for p in `cat $series`; do
	idx=`expr $idx + 1`
	[ $idx -lt $n ] && continue

	echo $p
done
