#!/bin/bash
#
# Copyright (c) Pierre Habouzit, 2007
#

USAGE="[<target_dir>]"
. guilt

if [ $# -gt 1 ]; then
	usage
fi
target_dir=${1:-"patches"}

if [ -e "$target_dir" ]; then
	die "Specified directory already exists"
fi

trap "rm -rf \"$target_dir\"" 0
mkdir -p "$target_dir"

get_series | tee "$target_dir/series" | while read p; do
	cp "$GUILT_DIR/$branch/$p" "$target_dir/$p"
done

trap - 0
echo "Series exported to \"$target_dir\" sucessfully."
