#!/bin/sh
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

USAGE=""
. `dirname $0`/guilt

if [ $# -ne 0 ]; then
	usage
fi

TOP=`get_top`

if [ -z "$TOP" ]; then
	die "No patches applied; try guilt-push first"
fi

refresh_patch "$TOP"

