#!/bin/sh
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

DO_NOT_CHECK_BRANCH_EXISTENCE=1

USAGE="[-n | -a]"
. `dirname $0`/guilt

AUTOTAG_DEFAULT=1

while case $# in 0) break ;; esac; do
	case $1 in
		-n)
			autotag=0
			;;
		-a)
			autotag=1
			;;
		*)
			usage
			;;
	esac
	shift
done

if [ -d "$GUILT_DIR/$branch" ]; then
	die "Branch $branch appears to be already initialized (GIT_DIR=$GIT_DIR)"
fi

[ ! -d "$GUILT_DIR" ] && mkdir "$GUILT_DIR"
mkdir -p "$GUILT_DIR/$branch"
touch "$GUILT_DIR/$branch/series"
touch "$GUILT_DIR/$branch/status"

mkdir -p "$GIT_DIR/hooks/guilt"
cat > "$GIT_DIR/hooks/guilt/delete" <<EOF
#!/bin/sh
# Usage: <script> <patch being removed>

echo "Removing patch '\$1'..."
EOF

# if there's no guilt.autotag config, set it to default
cur=`git config --int --get guilt.autotag`
if [ -z "$cur" -o ! -z "$autotag" ]; then
	[ -z "$autotag" ] && autotag=$AUTOTAG_DEFAULT

	git config --int --replace-all guilt.autotag $autotag
fi
