#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

USAGE=""
. guilt

if [ $# -ne 0 ]; then
	usage
fi

n=`wc -l < $applied`
n=`expr $n + 1`

get_series | awk "{ if (NR == $n) print \$0}"

