#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

USAGE="[-v]"
. guilt

while case "$#" in 0) break ;; esac
do
	case "$1" in
	-v)
		verbose=t ;;
	*)
		usage ;;
	esac
	shift
done

if ! [ $verbose ]; then
	get_series
else
	prefix='+'
	top=$(get_top)

	get_series |
	while read patch; do
		if [ $patch = $top ]; then
			echo '=' $patch
			prefix=' '
		else
			echo "$prefix" $patch
		fi
	done
fi
