#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

source "`dirname $0`/guilt"

if [ $# -ne 0 ]; then
	print_usage
	exit 1
fi

git-rev-parse --verify HEAD >/dev/null 2>&1 || IS_INITIAL=t

function print_status
{
	while read status name newname
	do
		case "$status" in
			M ) echo "M $name";;
			D*) echo "D $name";;
			T ) echo "T $name";;
			C*) echo "C $name -> $newname";;
			R*) echo "R $name -> $newname";;
			A*) echo "A $name";;
			U ) echo "U $name";;
		esac
	done
}

# added
if [ -z "$IS_INITIAL" ]; then
	# non-initial commit
	git-diff-index -M --cached --name-status --diff-filter=MDTCRA HEAD |
	sed -e '
		s/\\/\\\\/g
		s/ /\\ /g
	' | print_status
else
	# initial commit
	git-ls-files |
	sed -e '
		s/\\/\\\\/g
		s/ /\\ /g
		s/^/A /
	' | print_status
fi

# untracked
if [ -f "$GIT_DIR/info/exclude" ]; then
	git-ls-files -z --others \
	--exclude-from="$GIT_DIR/info/exclude" \
	--exclude-per-directory=.gitignore
else
	git-ls-files -z --others --exclude-per-directory=.gitignore
fi | xargs -0 -L 1 echo | while read n; do
	[ -z "$n" ] && continue
	echo "$n" | sed -e 's/^/? /'
done

