#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

source "`dirname $0`/guilt"

USAGE="$USAGE [-a | --all | <patchname>]"

if [ $# -gt 1 ]; then
	print_usage
	exit 1
fi

patch="$1"

if [ "$patch" = "--all" -o "$patch" = "-a" ]; then
	# we are supposed to push all patches, get the last one out of
	# series

	eidx=`get_series | wc -l`
	if [ $eidx -eq 0 ]; then
		echo "There are no patches to push" >&2
		exit 1
	fi
elif [ -z "$patch" ]; then
	# we are supposed to push only the next patch onto the stack

	eidx=`wc -l < $applied`
	eidx=`expr $eidx + 1`
else
	# we're supposed to push only up to a patch, make sure the patch is
	# in the series

	eidx=`get_series | grep -ne "^$patch\$" | cut -d: -f1`
	if [ $eidx -eq 0 ]; then
		echo "Patch $patch is not in the series" >&2
		exit 1
	fi
fi

# make sure that there are no unapplied changes
if ! must_commit_first; then
	echo "Uncommited changes detected. Refresh first." >&2
	exit 1
fi

# now, find the starting patch
sidx=`wc -l < $applied`
sidx=`expr $sidx + 1`

idx=0
for p in `get_series`; do
	idx=`expr $idx + 1`
	[ $idx -lt $sidx ] && continue
	[ $idx -gt $eidx ] && break

	echo "Applying patch..$p"
	if [ ! -f "$GUILT_DIR/$branch/$p" ]; then
		echo "Patch $patch does not exist. Aborting." >&2
		exit 1
	fi

	push_patch $p

	# bail if necessary
	if [ $? -eq 0 ]; then
		echo "Patch applied."
	else
		echo "Patch applied with rejects. Fix it up, and refresh." >&2
		exit 1
	fi
done

