#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

USAGE="[--git]"
. guilt

case $# in
	0)
		;;
	1)
		[ "$1" != "--git" ] && usage
		gdiff=t
		;;
esac

TOP=`get_top`

if [ -z "$TOP" ]; then
	die "No patches applied; try guilt-push first"
fi

refresh_patch "$TOP" "$gdiff"

