#!/bin/sh
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

USAGE="[-e] [<patchname>]"
. `dirname $0`/guilt

if [ $# -gt 2 ]; then
	usage
fi

if [ "$1" = "-e" ]; then
	edit=t
	shift
fi

patch="$1"

if [ -z "$patch" ]; then
	# use the patch that's on the top of the stack

	eidx=`wc -l < $applied`
	if [ $eidx -eq 0 ]; then
		die "Status file is empty"
	fi
else
	# use the specified patch

	eidx=`get_series | grep -ne "^$patch\$" | cut -d: -f1`
	if [ $eidx -eq 0 ]; then
		die "Patch $patch is not in the series"
	fi
fi

idx=0
for p in `get_series`; do
	idx=`expr $idx + 1`
	[ $idx -lt $eidx ] && continue
	[ $idx -gt $eidx ] && break

	if [ -z "$edit" ]; then
		do_get_header $GUILT_DIR/$branch/$p
	else
		do_get_full_header $GUILT_DIR/$branch/$p > /tmp/guilt.msg.$$
		do_get_patch  $GUILT_DIR/$branch/$p > /tmp/guilt.diff.$$
		$editor "/tmp/guilt.msg.$$"
		mv $GUILT_DIR/$branch/$p $GUILT_DIR/$branch/$p~
		cat /tmp/guilt.msg.$$ > $GUILT_DIR/$branch/$p
		cat /tmp/guilt.diff.$$ >> $GUILT_DIR/$branch/$p
	fi
done

