#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

source "`dirname $0`/guilt"

patch="$1"

if [ -z "$patch" ]; then
	echo "You must specify a patch to delete"
	exit 1
fi

p=`grep -e "^[0-9a-f]{40}:$patch\$" < "$applied"`
if [ ! -z "$p" ] ; then
	echo "Cannot delete an applied patch"
	exit 1
fi

ex -s -c ":%g/^[0-9a-f]{40}:$patch\$/d|:wq" "$series"
