#!/bin/sh
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

USAGE="[-c]"
. `dirname $0`/guilt

case $# in
	0)
		# just output the regular series-style applied list
		cat $applied | cut -d: -f 2-
	;;

	1)
		if [ "$1" != "-c" ]; then
			usage
		fi

		cat $applied | sed -e 's/:/ /'
	;;
	
	*)
		usage
		;;
esac
