#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2007
#

. guilt

if [ $# -gt 0 ]; then
	usage
fi

patch=`get_top`
if [ -z "$patch" ]; then
	die "No patches are applied."
fi

# make sure that there are no unapplied changes
if ! must_commit_first; then
	die "Uncommited changes detected. Refresh first."
fi

# Rename patches smartly
base=$(echo "$patch" \
	| sed -r -e 's:(\.diff?|\.patch)$::')
num=$(echo "$base" | sed -nre 's:.*-([0-9]+)$:\1:'p)
[ -n "$num" ] || num=1
newpatch="${base%-$num}-$((num+1))${patch#$base}"

# copy the patch
cp "$GUILT_DIR/$branch/$patch" "$GUILT_DIR/$branch/$newpatch"

# replace the series & applied file references
series_rename_patch "$patch" "$newpatch"
applied_rename_patch "$patch" "$newpatch"
