#!/bin/sh
#
# Copyright (c) Josef "Jeff" Sipek, 2007
#

DO_NOT_CHECK_BRANCH_EXISTENCE=1

USAGE="[<command> | <topic>]"
. `dirname $0`/guilt

case $# in
	0)
		page="guilt"
		;;
	1)
		case "$1" in
			guilt*)
				# guilt --help
				# guilt-cmd --help
				# guilt-help guilt-foo
				page="$1" ;;
			*)
				# guilt-help foo
				page="guilt-$1" ;;
		esac
		;;
	*)
		usage
		;;
esac

exec man "$page"
