#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

USAGE=""
. guilt

if [ $# -ne 0 ]; then
	usage
fi

n=`wc -l < $applied`
n=`expr $n + 1`

idx=0
for p in `get_series`; do
	idx=`expr $idx + 1`
	[ $idx -lt $n ] && continue

	echo $p
done
