#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2007
#

DO_NOT_CHECK_BRANCH_EXISTENCE=1

USAGE="[-n] [<hash> | <since>..[<until>] | ..<until>]"
. guilt

case $# in
	1)
		r="$1"
		;;
	2)
		r="$2"
		do_not_send=t

		if [ "$1" != "-n" ]; then
			usage
		fi
		;;
	*)
		usage
		;;
esac

r=`munge_hash_range $r`

# FIXME: allow in-reply-to

# display the list of commits to be sent as patches
git-log --pretty=oneline "$r" | cut -c 1-8,41- | $pager

echo -n "Are these what you want to send? [Y/n] "
read n
if [ "$n" = "n" -o "$n" = "N" ]; then
	die "Aborting..."
fi

dir=/tmp/patches-$RANDOM/
if [ -e $dir ]; then
	die "Conspiracy uncovered: Temporary dir '$dir' already exists"
fi
echo "Using '$dir' as temporary directory"

git-format-patch -o $dir -n -s "$r"

# get the to/cc addresses
echo -n "Enter all the To: email addresses (separated by space): "
read rawto
echo -n "Enter all the Cc: email addresses (separated by space): "
read rawcc

# convert list of email addresses to command line options
to_opts=""
for rt in $rawto; do
	to_opts="$to_opts --to $rt"
done
for rc in $rawcc; do
	to_opts="$to_opts --cc $rc"
done

opts=""
if [ `git-rev-list "$r" | wc -l` -gt 1 ]; then
	# more than 1 commit
	opts="--no-chain-reply-to --compose"
fi
opts="$opts $to_opts"

# last possible point to abort!
echo "About to execute 'git-send-email $opts $dir'"
echo -n "Proceed with patchbomb (this is the last chance to abort)? [y/N] "
read n
if [ "$n" != "y" -a "$n" != "Y" ]; then
	die "Aborting..."
fi

# ...and off they go.
if [ -z "$do_not_send" ]; then
	git-send-email $opts $dir
else
	echo "-n passed: not sending, command that would be executed:" >&2
	echo git-send-email $opts $dir
fi

# cleanup?
echo -n "Delete temporary directory? [Y/n] "
read n

[ "$n" != "n" -a "$n" != "N" ] && exit 0
rm -rf $dir
