#!/bin/sh
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

USAGE="[-p|--path]"
. `dirname $0`/guilt

while [ $# -ne 0 ]; do
	case "$1" in
	-p|--path)
		path="$GUILT_DIR/$branch/" ;;
	*)
		usage ;;
	esac
	shift
done

n=`wc -l < $applied`
n=$(($n + 1))

p=`get_series | awk "{ if (NR == $n) print \\$0}"`

if [ -n "$p" ]; then
	disp $path$p
fi
