#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

source "`dirname $0`/guilt"

USAGE="$USAGE <patchname>"

if [ $# -ne 1 ]; then
	print_usage
	exit 1
fi

patch="$1"

if [ -z "$patch" ]; then
	print_usage
	echo "You must specify a patch name"
	exit 1
fi

iidx=`wc -l < $applied`

# make sure that there are no unapplied changes
if ! must_commit_first; then
	echo "Uncommited changes detected. Refresh first."
	exit 1
fi

# create any directories as needed
[ "`dirname $patch`" != "." ] && mkdir -p `dirname $GUILT_DIR/$branch/$patch`

# create the empty patch file
touch $GUILT_DIR/$branch/$patch

top=`get_top`

if [ ! -z "$top" ]; then
	sed -i -e "s,^$top\$,$top\n$patch," $series
else
	echo "$patch" > $series.tmp
	cat $series >> $series.tmp
	mv $series.tmp $series
fi

# apply the patch
push_patch $patch
