#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

source "`dirname $0`/guilt"

if [ $# -ne 0 ]; then
	print_usage
	exit 1
fi

n=`wc -l < $applied`
n=`expr $n + 1`

get_series | awk "{ if (NR == $n) print \$0}"

