#!/bin/sh
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

USAGE="[-p|--path]"
. `dirname $0`/guilt

while [ $# -ne 0 ]; do
	case "$1" in
	-p|--path)
		path="$GUILT_DIR/$branch/" ;;
	*)
		usage ;;
	esac
	shift
done

p=`get_prev`

if [ -n "$p" ]; then
	echo $path$p
fi
