#!/bin/sh
#
# Copyright (c) Josef "Jeff" Sipek, 2007
#

DO_NOT_CHECK_BRANCH_EXISTENCE=1

USAGE="[<command> | <topic>]"
. `dirname $0`/guilt

case $# in
	0)
		page="guilt"
		;;
	1)
		if [ "$1" != "guilt" ]; then
			page="guilt-$1"
		else
			page="guilt"
		fi
		;;
	*)
		usage
		;;
esac

exec man "$page"
