#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

DO_NOT_CHECK_BRANCH_EXISTENCE=1

source "`dirname $0`/guilt"

USAGE=""

if [ -d "$GUILT_DIR/$branch" ]; then
	echo "Branch $branch appears to be already initialized (GIT_DIR=$GIT_DIR)"
	exit 1
fi

[ ! -d "$GUILT_DIR" ] && mkdir $GUILT_DIR
mkdir $GUILT_DIR/$branch
touch $GUILT_DIR/$branch/series
touch $GUILT_DIR/$branch/status

