#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

source "`dirname $0`/guilt"

USAGE="$USAGE <patchname>"

if [ $# -ne 1 ]; then
	print_usage
	exit 1
fi

patch="$1"

if [ -z "$patch" ]; then
	print_usage
	echo "You must specify a patch to delete"
	exit 1
fi

p=`grep -e "^$patch\$" < "$applied"`
if [ ! -z "$p" ] ; then
	echo "Cannot delete an applied patch"
	exit 1
fi

ex -s -c ":%g/^$patch\$/d|:wq" "$series"
