#!/bin/sh
#
# Copyright (C) 2007 Josef 'Jeff' Sipek <jeffpc@josefsipek.net>
#

USAGE="[-z] [<path>...]"
. `dirname $0`/guilt

while [ $# -ne 0 ]; do
	case "$1" in
	-z)
		working_tree=t ;;
	-* | --*)
		usage ;;

	*)
		break ;;
	esac
	shift
done

PREV=HEAD^
[ -z "`get_top`" ] && PREV=
[ ! -z "$working_tree" ] && PREV=

git diff $PREV -- "$@"
