#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

source "`dirname $0`/guilt"

USAGE="$USAGE [-c]"

case $# in
	0)
		# just output the regular series-style applied list
		cat $applied | cut -d: -f 2-
	;;

	1)
		if [ "$1" != "-c" ]; then
			print_usage
			exit 1
		fi

		cat $applied | sed -e 's/:/ /'
	;;
	
	*)
		print_usage
		exit 1
		;;
esac
