#!/bin/bash
#
# Copyright (c) Josef "Jeff" Sipek, 2006, 2007
#

source "`dirname $0`/guilt"

patch="$1"

if [ "$patch" = "--all" -o "$patch" = "-a" ]; then
	# we are supposed to pop all patches

	sidx=`wc -l < $applied`
	sidx=`expr $sidx - 1`
	eidx=0
elif [ -z "$patch" ]; then
	# we are supposed to pop only the current patch on the stack

	sidx=`wc -l < $applied`
	sidx=`expr $sidx - 1`
	eidx=$sidx
else
	# we're supposed to pop only up to a patch, make sure the patch is
	# in the series

	eidx=`cat $applied | grep -ne "^[0-9a-f]{40}$patch\$" | cut -d: -f 3-`
	if [ -z "$eidx" ]; then
		echo "Patch $patch is not in the series/is not applied"
		exit 1
	fi

	eidx=`expr $eidx - 1`
	sidx=`wc -l < $applied`
	sidx=`expr $sidx - 1`
fi

# make sure that there are no unapplied changes
if ! must_commit_first; then
	echo "Uncommited changes detected. Refresh first."
	exit 1
fi

idx=`get_series | wc -l`
for p in `get_series | tac`; do
	idx=`expr $idx - 1`
	[ $idx -gt $sidx ] && continue
	[ $idx -lt $eidx ] && break

	echo "Popping patch...$p"

	pop_patch
done

p=`get_top`
[ ! -z "$p" ] && echo "Now at $p." || echo "All patches popped."

