#!/bin/bash

set -e

export REPODIR=/tmp/$RANDOM

function empty_repo
{
	rm -rf $REPODIR || exit 1
	mkdir $REPODIR || exit 1
	cd $REPODIR
	git-init-db 2> /dev/null > /dev/null
}

function verify_repo
{
        ( find $1 -type d -printf 'd %p\n' ; find $1 -type f -printf 'f %p\n' ; find $1 -type b -printf 'b %p\n' ; find $1 -type c -printf %'c %p\n' ; find $1 -type l -printf 'l %p\n') | sort > /tmp/check-$$
        grep -v '^$' | sort | diff -u - /tmp/check-$$
        ERR=$?
        rm -f /tmp/check-$$
        return $ERR
}

function complete_test
{
	echo "OK"
	rm -rf $REPODIR
}

echo -n "`basename $0`: "
