.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GUILT\-DIFF" "1" "01/22/2015" "Guilt v0.36\-rc1" "Guilt Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt\-diff \- Outputs various diffs
.SH "SYNOPSIS"
\fIguilt\-diff\fR [\-z] [<path>\&...]
.SH "DESCRIPTION"
Outputs top\-most applied diff and any additional changes in the working directory to standard output.
.SH "OPTIONS"
.TP
\-z
Output a interdiff against the top\-most applied patch. This should produce the same diff as "guilt\-new \-f foo".
.TP
<path>\&...
Restrict diff output to a given set of files.
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <[1]\&\fIjeffpc@josefsipek.net\fR>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <[1]\&\fIjeffpc@josefsipek.net\fR>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.36\-rc1)
.SH "REFERENCES"
.TP 3
1.\ jeffpc@josefsipek.net
\%mailto:jeffpc@josefsipek.net
