.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GUILT\-PUSH" "1" "01/22/2015" "Guilt v0.36\-rc1" "Guilt Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt\-push \- Push patches onto the tree
.SH "SYNOPSIS"
\fIguilt\-push\fR [ \-f ] [\-a | \-\-all | \-n <num> | <patchname>]
.SH "OPTIONS"
.TP
\-f
Force the push if the patch doesn\(cqt apply cleanly
.TP
\-\-all , \-a
Push all patches on the tree
.TP
\-n <num>
Push specified number of patches
.TP
<patchname>
Push all patches up to and including this patch on the tree

If no patchname is given, push the next patch in the series onto the tree.

Exit with a non\-zero exit status if requested to push more patches than there are in the series.
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <[1]\&\fIjeffpc@josefsipek.net\fR>
.SH "DOCUMENTATION"
Documentation by Brandon Philips <[2]\&\fIbrandon@ifup.org\fR>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.36\-rc1)
.SH "REFERENCES"
.TP 3
1.\ jeffpc@josefsipek.net
\%mailto:jeffpc@josefsipek.net
.TP 3
2.\ brandon@ifup.org
\%mailto:brandon@ifup.org
