.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GUILT\-NEW" "1" "01/22/2015" "Guilt v0.36\-rc1" "Guilt Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt\-new \- Create a new patch
.SH "SYNOPSIS"
\fIguilt\-new\fR [\-f] [\-s] [\-e|\-m message] <patchname>
.SH "DESCRIPTION"
Create a new patch and push it on top of the stack. An optional patch description can be supplied either interactively on via the command line.
.SH "OPTIONS"
.TP
\-f
Force patch creation if there are unrefreshed changes. These changes will get automatically imported into the new patch.
.TP
\-s
Add a Signed\-off\-by with your committer identifier string to the patch message.
.TP
\-e
Edit the patch message interactively. This option can be combined with \-s to easily sign off on the patch.
.TP
\-m <message>
The "<message>" string will used as the commit message. This option can be combined with \-s to easily sign off on the patch.
.TP
<patchname>
Name of the patch to create. This must be a legal relative pathname string. For example, "foo", "foo/bar", and "foo/bar/foobar" are all valid.
.SH "EXAMPLES"
Create a new patch called \fIfoobar\fR:
.sp
.nf
$ guilt\-new foobar
.fi
Create a patch called \fIfoo\fR and supply a patch description interactively:
.sp
.nf
$ guilt\-new \-e foo
.fi
Create a patch called \fIbar\fR with a provided patch description and sign off on the patch:
.sp
.nf
$ guilt\-new \-s \-m patch\-fu bar
.fi
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <[1]\&\fIjeffpc@josefsipek.net\fR>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <[1]\&\fIjeffpc@josefsipek.net\fR>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.36\-rc1)
.SH "REFERENCES"
.TP 3
1.\ jeffpc@josefsipek.net
\%mailto:jeffpc@josefsipek.net
