.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GUILT\-REFRESH" "1" "01/22/2015" "Guilt v0.36\-rc1" "Guilt Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt\-refresh \- Refresh topmost applied patch
.SH "SYNOPSIS"
\fIguilt\-refresh\fR [\-\-git] [\-\-diffstat]
.SH "DESCRIPTION"
Refresh topmost applied patch with changes in the working copy.
.SH "OPTIONS"
.TP
\-\-git
Generate a patch which uses all the features offered by the git diff format (e.g., rename and copy detection).
.TP
\-\-diffstat
Include a diffstat output in the patch file. Useful for cases where patches will be submitted with other tools.

If the command line option is omitted, the corresponding git\-config option "guilt.diffstat" will be queried. So this would enable diffstat output by default:
.sp
.nf
git config \-\-global guilt.diffstat true
.fi
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <[1]\&\fIjeffpc@josefsipek.net\fR>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <[1]\&\fIjeffpc@josefsipek.net\fR>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.36\-rc1)
.SH "REFERENCES"
.TP 3
1.\ jeffpc@josefsipek.net
\%mailto:jeffpc@josefsipek.net
