.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GUILT" "7" "01/22/2015" "Guilt v0.36\-rc1" "Guilt Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt \- quilt on top of git
.SH "SYNOPSIS"
\fIguilt\fR COMMAND [ARGS]
.SH "DESCRIPTION"
Andrew Morton originally developed a set of scripts for maintaining kernel patches outside of any SCM tool. Others extended these into a suite called quilt. The basic idea behind quilt is to maintain patches instead of maintaining source files. Patches can be added, removed or reordered, and they can be refreshed as you fix bugs or update to a new base revision. quilt is very powerful, but it is not integrated with the underlying SCM tools. This makes it difficult to visualize your changes.

Guilt allows one to use quilt functionality on top of a Git repository. Changes are maintained as patches which are committed into Git. Commits can be removed or reordered, and the underlying patch can be refreshed based on changes made in the working directory. The patch directory can also be placed under revision control, so you can have a separate history of changes made to your patches.
.SH "PATCHES DIRECTORY"
In Guilt, all the patches are stored in .git/patches/$branch/, where $branch is the name of the branch being worked on. This means that one can have a independent series of patches for each branch present in the repository. Each of these per\-branch directories contains 3 special files:

guards: This file contains any guards that should be applied to the series when pushing. It is only present when guards are selected.

series: This file contains a list of all the patch filenames relative to the per\-branch patch directory. Empty and commented out lines are ignored.

status: This file contains the state of the stack. What patches are applied.
.SH "HOOKS"
Any guilt operation may execute zero or more hook scripts which can be used to run any housekeeping commands or even abort the execution of the command.
.SH "HOOKS DIRECTORY"
Guilt follows the same basic design of hooks in Git itself. All Guilt hooks are executable files (generally shell scripts, but they can be anything the operating system can execute) in .git/hooks/guilt/.

The following hooks are supported:
.TP
delete <patch name>
Executed when a patch is deleted from the patch series via \fBguilt\-delete\fR(1).
.SH "GUILT COMMANDS"
All commands can be called with or without a dash. e.g. \fIguilt add\fR or \fIguilt\-add\fR
.TP
\fBguilt\-add\fR(1)
guilt\-add \- Add a file to git and guilt.
.TP
\fBguilt\-applied\fR(1)
guilt\-applied \- List applied patches.
.TP
\fBguilt\-branch\fR(1)
guilt\-branch \- Branch the entire patch series.
.TP
\fBguilt\-commit\fR(1)
guilt\-commit \- Commit specified number of patches.
.TP
\fBguilt\-delete\fR(1)
guilt\-delete \- Delete a patch.
.TP
\fBguilt\-diff\fR(1)
guilt\-diff \- Outputs various diffs.
.TP
\fBguilt\-export\fR(1)
guilt\-export \- Export a patch series (to be used by quilt).
.TP
\fBguilt\-files\fR(1)
guilt\-files \- Print the list of files that the topmost patch changes.
.TP
\fBguilt\-fold\fR(1)
guilt\-fold \- Fold a specified patch into the topmost applied patch.
.TP
\fBguilt\-fork\fR(1)
guilt\-fork \- Fork the topmost applied patch.
.TP
\fBguilt\-graph\fR(1)
guilt\-graph \- Create a patch dependency graph.
.TP
\fBguilt\-guard\fR(1)
guilt\-guard \- Assign guards to patches.
.TP
\fBguilt\-header\fR(1)
guilt\-header \- Print a patch header.
.TP
\fBguilt\-help\fR(1)
guilt\-help \- open man page of a guilt command.
.TP
\fBguilt\-import\-commit\fR(1)
guilt\-import\-commit \- Import one or more commits as patches.
.TP
\fBguilt\-import\fR(1)
guilt\-import \- Import specified patch file.
.TP
\fBguilt\-init\fR(1)
guilt\-init \- Initialize guilt for use in a git repository.
.TP
\fBguilt\-new\fR(1)
guilt\-new \- Create a new patch.
.TP
\fBguilt\-next\fR(1)
guilt\-next \- Output the name of next patch to be pushed.
.TP
\fBguilt\-patchbomb\fR(1)
guilt\-patchbomb \- Email a series of commits interactively.
.TP
\fBguilt\-pop\fR(1)
guilt\-pop \- Pop patches from the tree.
.TP
\fBguilt\-prev\fR(1)
guilt\-prev \- Output name of second topmost applied patch.
.TP
\fBguilt\-push\fR(1)
guilt\-push \- Push patches onto the tree.
.TP
\fBguilt\-rebase\fR(1)
guilt\-rebase \- Rebase pushed patches.
.TP
\fBguilt\-refresh\fR(1)
guilt\-refresh \- Refresh topmost applied patch.
.TP
\fBguilt\-repair\fR(1)
guilt\-repair \- Repair the repository state.
.TP
\fBguilt\-rm\fR(1)
guilt\-rm \- Remove a file from the git tree and guilt.
.TP
\fBguilt\-select\fR(1)
guilt\-select \- Select guards to apply when pushing patches.
.TP
\fBguilt\-series\fR(1)
guilt\-series \- Print the stack of patches.
.TP
\fBguilt\-status\fR(1)
guilt\-status \- Print the status of files since the last refresh.
.TP
\fBguilt\-top\fR(1)
guilt\-top \- Output name of topmost applied patch.
.TP
\fBguilt\-unapplied\fR(1)
guilt\-unapplied \- List all unapplied patches.
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <[1]\&\fIjeffpc@josefsipek.net\fR>
.SH "DOCUMENTATION"
Documentation by Brandon Philips <[2]\&\fIbrandon@ifup.org\fR> and Josef "Jeff" Sipek <[1]\&\fIjeffpc@josefsipek.net\fR>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.36\-rc1)
.SH "REFERENCES"
.TP 3
1.\ jeffpc@josefsipek.net
\%mailto:jeffpc@josefsipek.net
.TP 3
2.\ brandon@ifup.org
\%mailto:brandon@ifup.org
