.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GUILT\-HEADER" "1" "01/22/2015" "Guilt v0.36\-rc1" "Guilt Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt\-header \- Print a patch header
.SH "SYNOPSIS"
\fIguilt\-header\fR [\-eE] [<patchname>]
.SH "DESCRIPTION"
Prints either the topmost patch\(cqs header or the header of a specified patch.
.TP
\-e
Open the header in an editor, instead of printing it.
.TP
\-E
Open the raw patch in an editor, instead of printing it.
.TP
<patchname>
Name of the patch. If a patch with exactly this name exists, use it. Otherwise, treat the name as a regexp; if the regexp matches a single patch, use it. Otherwise, list all matching patch names to stderr and fail.
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <[1]\&\fIjeffpc@josefsipek.net\fR>
.SH "DOCUMENTATION"
Documentation by Brandon Philips <[2]\&\fIbrandon@ifup.org\fR>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.36\-rc1)
.SH "REFERENCES"
.TP 3
1.\ jeffpc@josefsipek.net
\%mailto:jeffpc@josefsipek.net
.TP 3
2.\ brandon@ifup.org
\%mailto:brandon@ifup.org
