.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GUILT\-SERIES" "1" "01/22/2015" "Guilt v0.36\-rc1" "Guilt Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
guilt\-series \- Print the stack of patches
.SH "SYNOPSIS"
\fIguilt\-series\fR [\-v | \-g | \-e]
.SH "DESCRIPTION"
Print the stack of patches on this branch.
.SH "OPTIONS"
.TP
\-e
Edit the series file.
.TP
\-g
Instead of outputting the series, start gitk and display the applied patches. Ignores the verbose flag.
.TP
\-v
Verbose output; adds an = next to the top most applied patch, and a + to all other applied patches
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <[1]\&\fIjeffpc@josefsipek.net\fR>
.SH "DOCUMENTATION"
Documentation by Josef "Jeff" Sipek <[1]\&\fIjeffpc@josefsipek.net\fR>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0.36\-rc1)
.SH "REFERENCES"
.TP 3
1.\ jeffpc@josefsipek.net
\%mailto:jeffpc@josefsipek.net
